import React, { useState, useEffect } from 'react';
import {
  BarChart, Bar, LineChart, Line, FunnelChart, Funnel, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, LabelList
} from 'recharts';
import {
  Eye, Video, Heart, Bookmark, Share2, Navigation, QrCode, TrendingUp, 
  Sparkles, Clock, Smartphone, Monitor, Tablet, Loader2, AlertCircle, Download, X, ShoppingBag
} from 'lucide-react';
// Analytics V2 - Fresh start analytics system (cutover: 2026-03-19)
import {
  getPartnerSummaryV2,
  getTopItemsV2,
  getMostWatchedVideosV2,
  getPeakHoursV2,
  getDeviceBreakdownV2,
  getConversionFunnelV2,
  getDateRange,
  PartnerSummaryV2,
  TopItemV2,
  PeakHourV2,
  DeviceBreakdownV2,
  ConversionFunnelV2
} from '../../services/partnerAnalyticsV2Service';
import { ANALYTICS_V2_START_DATE } from '../../services/analyticsV2Service';
import { supabase } from '../../lib/supabase';

const COLORS = ['#f97316', '#fb923c', '#fdba74', '#fed7aa'];

interface RestaurantAnalyticsProps {
  restaurantId: string;
}

type DatePeriod = 'today' | '7days' | '30days';
type MetricType = 'video_plays' | 'likes' | 'saves' | 'shares' | 'order_clicks' | null;

const RestaurantAnalytics: React.FC<RestaurantAnalyticsProps> = ({ restaurantId }) => {
  const [period, setPeriod] = useState<DatePeriod>('7days');
  const [loading, setLoading] = useState(true);
  
  const [summary, setSummary] = useState<PartnerSummaryV2 | null>(null);
  const [funnel, setFunnel] = useState<ConversionFunnelV2 | null>(null);
  const [topItems, setTopItems] = useState<TopItemV2[]>([]);
  const [mostWatchedVideos, setMostWatchedVideos] = useState<TopItemV2[]>([]);
  const [peakHours, setPeakHours] = useState<PeakHourV2[]>([]);
  const [deviceBreakdown, setDeviceBreakdown] = useState<DeviceBreakdownV2 | null>(null);
  
  const [selectedMetric, setSelectedMetric] = useState<MetricType>(null);

  useEffect(() => {
    loadAnalytics();
  }, [restaurantId, period]);

  const [showDownloadMenu, setShowDownloadMenu] = useState(false);

  const downloadReport = (format: 'csv' | 'excel' | 'pdf') => {
    if (!summary) return;
    
    const { start, end } = getDateRange(period);
    const periodLabel = period === 'today' ? 'Today' : period === '7days' ? 'Last 7 Days' : 'Last 30 Days';
    const dateRange = `${start.toLocaleDateString()} - ${end.toLocaleDateString()}`;
    const filename = `analytics-report-${period}-${new Date().toISOString().split('T')[0]}`;

    if (format === 'csv') {
      // CSV Format
      let csv = `MenuLove Analytics Report\n`;
      csv += `Generated by MenuLove - Restaurant Analytics Platform\n`;
      csv += `Report Period: ${periodLabel}\n`;
      csv += `Date Range: ${dateRange}\n`;
      csv += `Website: menulove.com.au\n\n`;
      csv += `Summary\n`;
      csv += `Metric,Value\n`;
      csv += `Profile Views,${summary.profile_views}\n`;
      csv += `Item Views,${summary.item_views}\n`;
      csv += `Video Plays,${summary.video_plays}\n`;
      csv += `Video Completes,${summary.video_completes}\n`;
      csv += `Likes,${summary.likes}\n`;
      csv += `Saves,${summary.saves}\n`;
      csv += `Shares,${summary.shares}\n`;
      csv += `Order Clicks,${summary.order_clicks}\n`;
      csv += `Directions Clicks,${summary.directions_clicks}\n`;
      csv += `QR Scans,${summary.qr_scans}\n\n`;
      csv += `Top Performing Items\n`;
      csv += `Item Name,Category,Views,Plays,Likes,Saves,Shares,Engagement\n`;
      topItems.forEach(item => {
        csv += `${item.item_name},${item.item_type},${item.views},${item.video_plays},${item.likes},${item.saves},${item.shares},${item.engagement_rate}%\n`;
      });
      csv += `\nPeak Hours\n`;
      csv += `Hour,Views\n`;
      peakHours.forEach(ph => {
        csv += `${formatHour(ph.hour)},${ph.views}\n`;
      });

      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else if (format === 'excel') {
      // Excel Format (HTML table that Excel can open)
      let html = `<html><head><meta charset="utf-8"><title>MenuLove Analytics Report</title></head><body>`;
      html += `<div style="margin-bottom: 20px; padding: 15px; background-color: #f97316; color: white; border-radius: 8px;">`;
      html += `<h1 style="margin: 0; font-size: 24px;">MenuLove Analytics Report</h1>`;
      html += `<p style="margin: 5px 0 0 0; font-size: 12px;">Generated by MenuLove - Restaurant Analytics Platform | menulove.com.au</p>`;
      html += `</div>`;
      html += `<h2>Report Period: ${periodLabel}</h2>`;
      html += `<p><strong>Date Range:</strong> ${dateRange}</p>`;
      html += `<h2>Summary</h2>`;
      html += `<table border="1"><tr><th>Metric</th><th>Value</th></tr>`;
      html += `<tr><td>Profile Views</td><td>${summary.profile_views}</td></tr>`;
      html += `<tr><td>Item Views</td><td>${summary.item_views}</td></tr>`;
      html += `<tr><td>Video Plays</td><td>${summary.video_plays}</td></tr>`;
      html += `<tr><td>Video Completes</td><td>${summary.video_completes}</td></tr>`;
      html += `<tr><td>Likes</td><td>${summary.likes}</td></tr>`;
      html += `<tr><td>Saves</td><td>${summary.saves}</td></tr>`;
      html += `<tr><td>Shares</td><td>${summary.shares}</td></tr>`;
      html += `<tr><td>Order Clicks</td><td>${summary.order_clicks}</td></tr>`;
      html += `<tr><td>Directions Clicks</td><td>${summary.directions_clicks}</td></tr>`;
      html += `<tr><td>QR Scans</td><td>${summary.qr_scans}</td></tr>`;
      html += `</table>`;
      html += `<h2>Top Performing Items</h2>`;
      html += `<table border="1"><tr><th>Item Name</th><th>Category</th><th>Views</th><th>Plays</th><th>Likes</th><th>Saves</th><th>Shares</th><th>Engagement</th></tr>`;
      topItems.forEach(item => {
        html += `<tr><td>${item.item_name}</td><td>${item.item_type}</td><td>${item.views}</td><td>${item.video_plays}</td><td>${item.likes}</td><td>${item.saves}</td><td>${item.shares}</td><td>${item.engagement_rate}%</td></tr>`;
      });
      html += `</table></body></html>`;

      const blob = new Blob([html], { type: 'application/vnd.ms-excel' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.xls`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else if (format === 'pdf') {
      // PDF Format (using print)
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>MenuLove Analytics Report</title>
              <style>
                body { font-family: Arial, sans-serif; padding: 20px; }
                .header { background-color: #f97316; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
                .header h1 { margin: 0; font-size: 28px; }
                .header p { margin: 5px 0 0 0; font-size: 12px; opacity: 0.9; }
                h2 { color: #f97316; }
                table { border-collapse: collapse; width: 100%; margin: 20px 0; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #f97316; color: white; }
                .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #f97316; text-align: center; color: #666; font-size: 12px; }
              </style>
            </head>
            <body>
              <div class="header">
                <h1>MenuLove Analytics Report</h1>
                <p>Generated by MenuLove - Restaurant Analytics Platform | menulove.com.au</p>
              </div>
              <h2>Report Period: ${periodLabel}</h2>
              <p><strong>Date Range:</strong> ${dateRange}</p>
              <h2>Summary</h2>
              <table>
                <tr><th>Metric</th><th>Value</th></tr>
                <tr><td>Profile Views</td><td>${summary.profile_views}</td></tr>
                <tr><td>Item Views</td><td>${summary.item_views}</td></tr>
                <tr><td>Video Plays</td><td>${summary.video_plays}</td></tr>
                <tr><td>Video Completes</td><td>${summary.video_completes}</td></tr>
                <tr><td>Likes</td><td>${summary.likes}</td></tr>
                <tr><td>Saves</td><td>${summary.saves}</td></tr>
                <tr><td>Shares</td><td>${summary.shares}</td></tr>
                <tr><td>Order Clicks</td><td>${summary.order_clicks}</td></tr>
                <tr><td>Directions Clicks</td><td>${summary.directions_clicks}</td></tr>
                <tr><td>QR Scans</td><td>${summary.qr_scans}</td></tr>
              </table>
              <h2>Top Performing Items</h2>
              <table>
                <tr><th>Item Name</th><th>Category</th><th>Views</th><th>Plays</th><th>Likes</th><th>Saves</th><th>Shares</th><th>Engagement</th></tr>
                ${topItems.map(item => `<tr><td>${item.item_name}</td><td>${item.item_type}</td><td>${item.views}</td><td>${item.video_plays}</td><td>${item.likes}</td><td>${item.saves}</td><td>${item.shares}</td><td>${item.engagement_rate}%</td></tr>`).join('')}
              </table>
              <div class="footer">
                <p><strong>MenuLove</strong> - Restaurant Analytics Platform</p>
                <p>menulove.com.au | Powered by MenuLove</p>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
    
    setShowDownloadMenu(false);
  };

  const loadAnalytics = async () => {
    setLoading(true);
    try {
      const { start, end } = getDateRange(period);
      
      // Analytics V2 - Load from analytics_events table only
      const [summaryData, funnelData, itemsData, videosData, hoursData, deviceData] = await Promise.all([
        getPartnerSummaryV2(restaurantId, start, end),
        getConversionFunnelV2(restaurantId, start, end),
        getTopItemsV2(restaurantId, start, end, 10),
        getMostWatchedVideosV2(restaurantId, start, end, 8),
        getPeakHoursV2(restaurantId, start, end),
        getDeviceBreakdownV2(restaurantId, start, end)
      ]);

      setSummary(summaryData);
      setFunnel(funnelData);
      setTopItems(itemsData);
      setMostWatchedVideos(videosData);
      setPeakHours(hoursData);
      setDeviceBreakdown(deviceData);
    } catch (error) {
      console.error('[RestaurantAnalytics] Error loading analytics:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <Loader2 className="animate-spin text-orange-500" size={40} />
      </div>
    );
  }

  const hasData = summary && (summary.profile_views > 0 || summary.item_views > 0);

  return (
    <div className="space-y-6 pb-8">
      {/* Header with Period Filter */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-zinc-900">Your Analytics</h2>
          <p className="text-sm text-zinc-500 mt-1">Business intelligence for your restaurant</p>
        </div>
        
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={() => setPeriod('today')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              period === 'today'
                ? 'bg-orange-500 text-white'
                : 'bg-white border border-zinc-200 text-zinc-700 hover:bg-zinc-50'
            }`}
          >
            Today
          </button>
          <button
            onClick={() => setPeriod('7days')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              period === '7days'
                ? 'bg-orange-500 text-white'
                : 'bg-white border border-zinc-200 text-zinc-700 hover:bg-zinc-50'
            }`}
          >
            Last 7 Days
          </button>
          <button
            onClick={() => setPeriod('30days')}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              period === '30days'
                ? 'bg-orange-500 text-white'
                : 'bg-white border border-zinc-200 text-zinc-700 hover:bg-zinc-50'
            }`}
          >
            Last 30 Days
          </button>
          <div className="relative">
            <button
              onClick={() => setShowDownloadMenu(!showDownloadMenu)}
              disabled={!hasData}
              className="px-4 py-2 rounded-lg text-sm font-medium transition-colors bg-white border border-zinc-200 text-zinc-700 hover:bg-zinc-50 disabled:bg-zinc-100 disabled:text-zinc-400 disabled:cursor-not-allowed flex items-center gap-2"
            >
              <Download size={16} />
              Download Report
            </button>
            {showDownloadMenu && hasData && (
              <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-zinc-200 py-2 z-10">
                <button
                  onClick={() => downloadReport('csv')}
                  className="w-full px-4 py-2 text-left text-sm text-zinc-700 hover:bg-zinc-50 flex items-center gap-2"
                >
                  <Download size={14} />
                  Download CSV
                </button>
                <button
                  onClick={() => downloadReport('excel')}
                  className="w-full px-4 py-2 text-left text-sm text-zinc-700 hover:bg-zinc-50 flex items-center gap-2"
                >
                  <Download size={14} />
                  Download Excel
                </button>
                <button
                  onClick={() => downloadReport('pdf')}
                  className="w-full px-4 py-2 text-left text-sm text-zinc-700 hover:bg-zinc-50 flex items-center gap-2"
                >
                  <Download size={14} />
                  Download PDF
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Empty State */}
      {!hasData && (
        <div className="bg-white rounded-xl border border-zinc-200 p-12 text-center">
          <TrendingUp size={48} className="text-zinc-300 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-zinc-900 mb-2">No data yet</h3>
          <p className="text-sm text-zinc-500 max-w-md mx-auto mb-4">
            Your analytics will appear here once people start viewing your profile and menu items.
          </p>
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4 max-w-md mx-auto">
            <p className="text-sm text-orange-800 font-medium mb-2">How to get started:</p>
            <ul className="text-xs text-orange-700 space-y-1 text-left">
              <li>• Share your MenuLove profile link on social media</li>
              <li>• Place your QR code at the counter or on tables</li>
              <li>• Add your link to your website and Google Business</li>
            </ul>
          </div>
        </div>
      )}

      {hasData && (
        <>
          {/* Quick Stats - Views, Saves, Likes */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-white rounded-xl p-4 sm:p-6 border border-zinc-200 group relative">
              <div className="flex items-center gap-2 text-zinc-500 mb-2">
                <Eye size={18} />
                <span className="text-xs font-medium">Total Views</span>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{(summary?.profile_views || 0).toLocaleString()}</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex flex-col justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-900 font-semibold mb-2">Profile Views</p>
                <p className="text-xs text-zinc-600 leading-relaxed">
                  Total number of times customers opened your restaurant profile page
                </p>
              </div>
            </div>
            <button 
              onClick={() => setSelectedMetric('saves')}
              className="bg-white rounded-xl p-4 sm:p-6 border border-zinc-200 group relative hover:border-orange-300 hover:shadow-md transition-all cursor-pointer text-left w-full"
            >
              <div className="flex items-center gap-2 text-zinc-500 mb-2 group-hover:text-orange-600 transition-colors">
                <Bookmark size={18} />
                <span className="text-xs font-medium">Saves</span>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{(summary?.saves || 0).toLocaleString()}</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Click to see which videos were saved
                </p>
              </div>
            </button>
            <button 
              onClick={() => setSelectedMetric('likes')}
              className="bg-white rounded-xl p-4 sm:p-6 border border-zinc-200 group relative hover:border-orange-300 hover:shadow-md transition-all cursor-pointer text-left w-full"
            >
              <div className="flex items-center gap-2 text-zinc-500 mb-2 group-hover:text-orange-600 transition-colors">
                <Heart size={18} />
                <span className="text-xs font-medium">Likes</span>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{(summary?.likes || 0).toLocaleString()}</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Click to see which videos were liked
                </p>
              </div>
            </button>
          </div>


          {/* Summary Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
            <div className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-zinc-100 rounded-lg flex items-center justify-center">
                  <Eye size={20} className="text-zinc-600" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.profile_views || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">Profile Views</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Number of people who opened your restaurant profile page
                </p>
              </div>
            </div>

            <div id="tour-view-counter" className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-zinc-100 rounded-lg flex items-center justify-center">
                  <Eye size={20} className="text-zinc-600" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.item_views || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">Item Views</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Individual dish/video views. See "Top Performing Items" below for details on which dishes were viewed
                </p>
              </div>
            </div>

            <button 
              onClick={() => setSelectedMetric('video_plays')}
              className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative hover:border-orange-300 hover:shadow-md transition-all cursor-pointer text-left w-full"
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-zinc-100 rounded-lg flex items-center justify-center group-hover:bg-orange-100 transition-colors">
                  <Video size={20} className="text-zinc-600 group-hover:text-orange-600 transition-colors" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.video_plays || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">Video Plays</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Click to see which videos were played
                </p>
              </div>
            </button>

            <button 
              onClick={() => setSelectedMetric('order_clicks')}
              className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative hover:border-orange-300 hover:shadow-md transition-all cursor-pointer text-left w-full"
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center group-hover:bg-orange-200 transition-colors">
                  <ShoppingBag size={20} className="text-orange-600" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.order_clicks || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">Order Clicks</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Click to see which items received order clicks
                </p>
              </div>
            </button>

            <div className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-zinc-100 rounded-lg flex items-center justify-center">
                  <Navigation size={20} className="text-zinc-600" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.directions_clicks || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">Directions</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Number of times customers clicked "Get Directions" to navigate to your restaurant
                </p>
              </div>
            </div>

            <div className="bg-white rounded-xl border border-zinc-200 p-4 sm:p-6 group relative">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 bg-zinc-100 rounded-lg flex items-center justify-center">
                  <QrCode size={20} className="text-zinc-600" />
                </div>
              </div>
              <p className="text-2xl sm:text-3xl font-bold text-zinc-900">{summary?.qr_scans || 0}</p>
              <p className="text-xs sm:text-sm text-zinc-500 mt-1">QR Scans</p>
              <div className="absolute inset-0 bg-white rounded-xl p-4 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none flex items-center justify-center shadow-lg border border-zinc-200">
                <p className="text-xs text-zinc-700 text-center leading-relaxed">
                  Number of times customers scanned your QR code to view your menu
                </p>
              </div>
            </div>
          </div>

          {/* Most Watched Videos */}
          <div className="bg-white rounded-xl border border-zinc-200 p-6">
            <h3 className="text-lg font-bold text-zinc-900 mb-2">Most Watched Videos</h3>
            <p className="text-sm text-zinc-500 mb-4">See which dish videos customers are watching</p>
            
            {topItemsWithMedia.length > 0 ? (
              <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                {topItemsWithMedia.slice(0, 8).map((item, index) => (
                  <div key={item.item_id} className="group relative">
                    <div className="aspect-[9/16] bg-zinc-100 rounded-xl overflow-hidden relative">
                      {item.video_url ? (
                        <video
                          src={`${item.video_url}#t=0.5`}
                          className="w-full h-full object-cover"
                          muted
                          playsInline
                          preload="metadata"
                        />
                      ) : item.photo_url ? (
                        <img
                          src={item.photo_url}
                          className="w-full h-full object-cover"
                          alt={item.item_name}
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center bg-zinc-200">
                          <Video size={32} className="text-zinc-400" />
                        </div>
                      )}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
                      <div className="absolute top-2 left-2 w-6 h-6 bg-orange-500 rounded-full flex items-center justify-center">
                        <span className="text-xs font-bold text-white">{index + 1}</span>
                      </div>
                      <div className="absolute bottom-0 left-0 right-0 p-3">
                        <p className="text-white text-sm font-semibold line-clamp-2 mb-1">{item.item_name}</p>
                        <div className="flex items-center gap-2 text-white/90">
                          <Video size={12} />
                          <span className="text-xs font-medium">{item.video_plays} plays</span>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-12">
                <Video size={48} className="text-zinc-300 mx-auto mb-4" />
                <p className="text-sm font-medium text-zinc-900 mb-2">No video plays yet</p>
                <p className="text-xs text-zinc-500 max-w-md mx-auto">
                  When customers watch your dish videos, you'll see which ones are most popular here
                </p>
              </div>
            )}
          </div>

          {/* Conversion Funnel */}
          {funnel.length > 0 && (
            <div className="bg-white rounded-xl border border-zinc-200 p-6">
              <h3 className="text-lg font-bold text-zinc-900 mb-4">Conversion Funnel</h3>
              <div className="space-y-3">
                {funnel.map((step, index) => (
                  <div key={index} className="relative">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2 flex-1 min-w-0">
                        <span className="text-sm font-medium text-zinc-700 whitespace-nowrap">{step.step}</span>
                        {step.step === 'Item Views' && (
                          <span className="text-xs text-zinc-400 whitespace-nowrap">(clicked on dishes)</span>
                        )}
                        {step.step === 'Video Plays' && (
                          <span className="text-xs text-zinc-400 whitespace-nowrap">(watched videos)</span>
                        )}
                        {step.step === 'Directions' && (
                          <span className="text-xs text-zinc-400 whitespace-nowrap">(clicked get directions)</span>
                        )}
                        {step.step === 'QR Scans' && (
                          <span className="text-xs text-zinc-400 whitespace-nowrap">(scanned QR code)</span>
                        )}
                      </div>
                      <div className="flex items-center gap-3 flex-shrink-0">
                        <span className="text-sm font-bold text-zinc-900">{step.count}</span>
                        <span className="text-xs text-zinc-500 w-12 text-right">{step.conversion_rate}%</span>
                      </div>
                    </div>
                    <div className="w-full bg-zinc-100 rounded-full h-3">
                      <div 
                        className="bg-gradient-to-r from-orange-500 to-orange-400 h-3 rounded-full transition-all duration-500"
                        style={{ width: `${Math.min(step.conversion_rate, 100)}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
              <p className="text-xs text-zinc-500 mt-4">
                Shows customer journey: Profile Views → Item Views (clicked dishes) → Video Plays (watched videos) → Directions (clicked get directions) / QR Scans (scanned QR code)
              </p>
            </div>
          )}

          {/* Top Performing Items */}
          <div className="bg-white rounded-xl border border-zinc-200 p-6">
            <h3 className="text-lg font-bold text-zinc-900 mb-4">Top Performing Items</h3>
            <p className="text-sm text-zinc-500 mb-4">See exactly which dishes customers are viewing and engaging with</p>
            
            {topItems.length > 0 ? (
              <>
                <div className="overflow-x-auto -mx-6 px-6">
                  <table className="w-full min-w-[640px]">
                    <thead>
                      <tr className="border-b border-zinc-200">
                        <th className="text-left py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">Item</th>
                        <th className="text-center py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">Views</th>
                        <th className="text-center py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">Plays</th>
                        <th className="text-center py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">
                          <Heart size={12} className="inline" />
                        </th>
                        <th className="text-center py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">
                          <Bookmark size={12} className="inline" />
                        </th>
                        <th className="text-center py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">
                          <Share2 size={12} className="inline" />
                        </th>
                        <th className="text-right py-3 px-2 text-xs font-semibold text-zinc-600 uppercase">Engagement</th>
                      </tr>
                    </thead>
                    <tbody>
                      {topItems.map((item, index) => (
                        <tr key={item.item_id} className="border-b border-zinc-100 hover:bg-zinc-50">
                          <td className="py-3 px-2">
                            <div className="flex items-center gap-2">
                              <span className="w-6 h-6 bg-orange-100 rounded-full flex items-center justify-center text-xs font-bold text-orange-600">
                                {index + 1}
                              </span>
                              <div>
                                <p className="text-sm font-medium text-zinc-900">{item.item_name}</p>
                                <p className="text-xs text-zinc-500">{item.item_type}</p>
                              </div>
                            </div>
                          </td>
                          <td className="py-3 px-2 text-center text-sm font-semibold text-zinc-900">{item.views}</td>
                          <td className="py-3 px-2 text-center text-sm text-zinc-700">{item.video_plays}</td>
                          <td className="py-3 px-2 text-center text-sm text-zinc-700">{item.likes}</td>
                          <td className="py-3 px-2 text-center text-sm text-zinc-700">{item.saves}</td>
                          <td className="py-3 px-2 text-center text-sm text-zinc-700">{item.shares}</td>
                          <td className="py-3 px-2 text-right">
                            <span className={`px-2 py-1 rounded-full text-xs font-bold ${
                              item.engagement_rate >= 10 ? 'bg-green-100 text-green-700' :
                              item.engagement_rate >= 5 ? 'bg-orange-100 text-orange-700' :
                              'bg-zinc-100 text-zinc-600'
                            }`}>
                              {item.engagement_rate}%
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="text-xs text-zinc-500 mt-4">
                  Engagement Rate = (Likes + Saves + Shares) / Views
                </p>
              </>
            ) : (
              <div className="text-center py-12">
                <TrendingUp size={48} className="text-zinc-300 mx-auto mb-4" />
                <p className="text-sm font-medium text-zinc-900 mb-2">No item views yet</p>
                <p className="text-xs text-zinc-500 max-w-md mx-auto">
                  When customers click on your dishes to view details, you'll see which items are most popular here with detailed metrics for each dish.
                </p>
              </div>
            )}
          </div>

          {/* This Week Highlights */}
          {insights.length > 0 && (
            <div className="bg-gradient-to-br from-orange-50 to-amber-50 rounded-xl border-2 border-orange-200 p-6">
              <div className="flex items-center gap-2 mb-4">
                <Sparkles size={20} className="text-orange-600" />
                <h3 className="text-lg font-bold text-zinc-900">This Week Highlights</h3>
              </div>
              <ul className="space-y-2">
                {insights.map((insight, index) => (
                  <li key={index} className="text-sm text-zinc-700 flex items-start gap-2">
                    <span className="text-orange-500 mt-1 font-bold">•</span>
                    <span>{insight.insight_text}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Peak Hours Chart */}
          {peakHours.length > 0 && (
            <div className="bg-white rounded-xl border border-zinc-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-lg font-bold text-zinc-900">Peak Hours</h3>
                  <p className="text-xs text-zinc-400 mt-0.5">Brisbane time (AEST/AEDT)</p>
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 bg-orange-100 rounded-lg">
                  <Clock size={16} className="text-orange-600" />
                  <span className="text-sm font-bold text-orange-700">{getPeakWindow(peakHours)}</span>
                </div>
              </div>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={peakHours}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f4f4f5" />
                  <XAxis 
                    dataKey="hour" 
                    stroke="#71717a" 
                    fontSize={11}
                    tickFormatter={(hour) => formatHour(hour)}
                  />
                  <YAxis stroke="#71717a" fontSize={11} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#fff', 
                      border: '1px solid #e4e4e7',
                      borderRadius: '8px',
                      fontSize: '12px'
                    }}
                    labelFormatter={(hour) => formatHour(Number(hour))}
                  />
                  <Bar dataKey="views" fill="#f97316" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
              <p className="text-xs text-zinc-500 mt-4">
                Shows when your profile gets the most views throughout the day (Brisbane timezone)
              </p>
            </div>
          )}

          {/* Device Breakdown */}
          {summary && (
            <div className="bg-white rounded-xl border border-zinc-200 p-6">
              <h3 className="text-lg font-bold text-zinc-900 mb-4">Device Breakdown</h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="p-4 bg-orange-50 rounded-lg border border-orange-100">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-orange-500 rounded-lg flex items-center justify-center">
                      <Smartphone size={20} className="text-white" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-zinc-900">Mobile</p>
                      <p className="text-2xl font-bold text-orange-600">{summary.mobile_percentage}%</p>
                    </div>
                  </div>
                  <div className="w-full bg-orange-200 rounded-full h-2">
                    <div 
                      className="bg-orange-500 h-2 rounded-full transition-all"
                      style={{ width: `${summary.mobile_percentage}%` }}
                    />
                  </div>
                </div>

                <div className="p-4 bg-zinc-50 rounded-lg border border-zinc-200">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-zinc-200 rounded-lg flex items-center justify-center">
                      <Monitor size={20} className="text-zinc-600" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-zinc-900">Desktop</p>
                      <p className="text-2xl font-bold text-zinc-700">{summary.desktop_percentage}%</p>
                    </div>
                  </div>
                  <div className="w-full bg-zinc-200 rounded-full h-2">
                    <div 
                      className="bg-zinc-500 h-2 rounded-full transition-all"
                      style={{ width: `${summary.desktop_percentage}%` }}
                    />
                  </div>
                </div>

                <div className="p-4 bg-zinc-50 rounded-lg border border-zinc-200">
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-zinc-200 rounded-lg flex items-center justify-center">
                      <Tablet size={20} className="text-zinc-600" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-zinc-900">Tablet</p>
                      <p className="text-2xl font-bold text-zinc-700">{summary.tablet_percentage}%</p>
                    </div>
                  </div>
                  <div className="w-full bg-zinc-200 rounded-full h-2">
                    <div 
                      className="bg-zinc-500 h-2 rounded-full transition-all"
                      style={{ width: `${summary.tablet_percentage}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {/* Metric Detail Modal */}
      {selectedMetric && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={() => setSelectedMetric(null)}>
          <div className="bg-white rounded-xl max-w-4xl w-full max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between p-6 border-b border-zinc-200">
              <div>
                <h3 className="text-xl font-bold text-zinc-900">
                  {selectedMetric === 'video_plays' && 'Video Plays'}
                  {selectedMetric === 'likes' && 'Likes'}
                  {selectedMetric === 'saves' && 'Saves'}
                  {selectedMetric === 'shares' && 'Shares'}
                  {selectedMetric === 'order_clicks' && 'Order Clicks'}
                </h3>
                <p className="text-sm text-zinc-500 mt-1">
                  Items ranked by {selectedMetric === 'video_plays' ? 'plays' : selectedMetric === 'order_clicks' ? 'clicks' : selectedMetric}
                </p>
              </div>
              <button 
                onClick={() => setSelectedMetric(null)}
                className="w-10 h-10 rounded-full hover:bg-zinc-100 flex items-center justify-center transition-colors"
              >
                <X size={20} className="text-zinc-600" />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto max-h-[calc(90vh-100px)]">
              {topItems.length > 0 ? (
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                  {topItems
                    .sort((a, b) => {
                      if (selectedMetric === 'video_plays') return b.video_plays - a.video_plays;
                      if (selectedMetric === 'likes') return b.likes - a.likes;
                      if (selectedMetric === 'saves') return b.saves - a.saves;
                      if (selectedMetric === 'shares') return b.shares - a.shares;
                      if (selectedMetric === 'order_clicks') return b.shares - a.shares; // Using shares as proxy for now
                      return 0;
                    })
                    .filter(item => {
                      if (selectedMetric === 'video_plays') return item.video_plays > 0;
                      if (selectedMetric === 'likes') return item.likes > 0;
                      if (selectedMetric === 'saves') return item.saves > 0;
                      if (selectedMetric === 'shares') return item.shares > 0;
                      if (selectedMetric === 'order_clicks') return item.shares > 0; // Using shares as proxy for now
                      return false;
                    })
                    .map((item, index) => (
                      <div key={item.item_id} className="group relative">
                        <div className="aspect-[9/16] bg-zinc-100 rounded-xl overflow-hidden relative">
                          <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                          <div className="absolute top-2 left-2 w-6 h-6 bg-orange-500 rounded-full flex items-center justify-center">
                            <span className="text-xs font-bold text-white">{index + 1}</span>
                          </div>
                          <div className="absolute bottom-0 left-0 right-0 p-3">
                            <p className="text-white text-sm font-semibold line-clamp-2 mb-1">{item.item_name}</p>
                            <div className="flex items-center gap-2">
                              {selectedMetric === 'video_plays' && (
                                <>
                                  <Video size={14} className="text-white" />
                                  <span className="text-white text-xs font-bold">{item.video_plays}</span>
                                </>
                              )}
                              {selectedMetric === 'likes' && (
                                <>
                                  <Heart size={14} className="text-white" />
                                  <span className="text-white text-xs font-bold">{item.likes}</span>
                                </>
                              )}
                              {selectedMetric === 'saves' && (
                                <>
                                  <Bookmark size={14} className="text-white" />
                                  <span className="text-white text-xs font-bold">{item.saves}</span>
                                </>
                              )}
                              {selectedMetric === 'shares' && (
                                <>
                                  <Share2 size={14} className="text-white" />
                                  <span className="text-white text-xs font-bold">{item.shares}</span>
                                </>
                              )}
                              {selectedMetric === 'order_clicks' && (
                                <>
                                  <ShoppingBag size={14} className="text-white" />
                                  <span className="text-white text-xs font-bold">{item.shares}</span>
                                </>
                              )}
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <TrendingUp size={48} className="text-zinc-300 mx-auto mb-4" />
                  <p className="text-sm font-medium text-zinc-900 mb-2">No data yet</p>
                  <p className="text-xs text-zinc-500 max-w-md mx-auto">
                    When customers interact with your menu items, you'll see the details here.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default RestaurantAnalytics;
